### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [lesterdc/ISII-WORKSHOPS-Distribuidora_de_Pescado#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by lesterdc** [comment]
We will proceed to process the request, @lesterdc  will be the assigned analyst, @angtdiaz will develop the solution, and @Javiervinus will perform the tests.

**Comment by jose598** [comment]
Thank you @lesterdc

**Comment by lesterdc** [comment]
![image](https://user-images.githubusercontent.com/50631932/150031820-98efd183-6934-46d8-87e6-79bb38db482d.png)
This is the average time in which we will take to perform the respective tasks, it informs us if there is any problem in the planning of the same.

**Comment by jose598** [comment]
Hi @lesterdc. It's fine that you only waste 8 hours for working on this issue, anywise you have until 21 Feb. I have an observation about you last report about the issue analytics. For me, it's important to know how you are calculating the insurance results, it means that I will like that you send me a table with whole cases/rules applied with base conditions.

**Comment by lesterdc** [comment]
[Average_time.xlsx](https://github.com/lesterdc/ISII-WORKSHOPS-Distribuidora_de_Pescado/files/7917329/Average_time.xlsx)
Sorry for the delay, I am attaching the table below with a little more detail.

**Comment by jose598** [comment]
Thank you!
Start working on the next steps
